name: compile

on:
  push

jobs:
  build_paper:
    runs-on: ubuntu-latest

    steps:
      - uses: cvxgrp/.github/actions/latex@main
        with:
          paper: 'main.tex'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
